
package br.com.guaraba.wally.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AnunciosWebServiceService", targetNamespace = "http://ws.wally.guaraba.com.br/", wsdlLocation = "http://localhost:8080/guaraba-wally-ws/anuncios?wsdl")
public class AnunciosWebServiceService
    extends Service
{

    private final static URL ANUNCIOSWEBSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/guaraba-wally-ws/anuncios?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ANUNCIOSWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public AnunciosWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnunciosWebServiceService() {
        super(ANUNCIOSWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://ws.wally.guaraba.com.br/", "AnunciosWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns AnunciosWebService
     */
    @WebEndpoint(name = "AnunciosWebServicePort")
    public AnunciosWebService getAnunciosWebServicePort() {
        return (AnunciosWebService)super.getPort(new QName("http://ws.wally.guaraba.com.br/", "AnunciosWebServicePort"), AnunciosWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnunciosWebService
     */
    @WebEndpoint(name = "AnunciosWebServicePort")
    public AnunciosWebService getAnunciosWebServicePort(WebServiceFeature... features) {
        return (AnunciosWebService)super.getPort(new QName("http://ws.wally.guaraba.com.br/", "AnunciosWebServicePort"), AnunciosWebService.class, features);
    }

}
